-- the first script for migration
    create table Fn03Record (
        seq bigint generated by default as identity,
        amount integer not null,
        displayFlag varchar(255),
        name varchar(255),
        primary key (seq)
    )
    create table Fn01Record (
        seq bigint not null,
        ym varchar(255) not null,
        amount integer not null,
        primary key (seq, ym)
    )
